version: '2.6.0'

services:
  ngnix:
    container_name: nginx
    build: ./requirements/nginx/
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - www:/home/www/
    networks: 
      - wordpress
    depends_on:
      - wordpress
      - db
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - www:/home/www/
    networks:
      - wordpress
      - database
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: db
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql
    user: mysql
    networks:
      - database
    env_file:
      - .env
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - www:/var/www/html
    networks:
      - wordpress
    env_file:
      - .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - wordpress
    depends_on:
      - wordpress
      - db

volumes:
  db:
  www:

networks:
  wordpress:
  database:


  

