version: '2.6.0'

services:
  ngnix:
    container_name: nginx
    build: ./requirements/nginx/
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/wordpress/www:/home/www/:delegated
    networks: 
      - wordpress
    depends_on:
      - wordpress
      - db
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - ./requirements/wordpress/www:/home/www/
    networks:
      - wordpress
      - database
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: db
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./requirements/mariadb/db:/var/lib/mysql
    networks:
      - database
    env_file:
      - .env

networks:
  wordpress:
  database:


  

